<?php

namespace Database\Seeders;

use App\Models\Specialty;
use Illuminate\Database\Seeder;

class SpecialtySeeder extends Seeder
{
    public function run(): void
    {
        $specialties = [
            ['id' => 1, 'name' => 'Medicina General', 'description' => '', 'status' => true],
            ['id' => 2, 'name' => 'Psicólogia', 'description' => '', 'status' => true],
            ['id' => 3, 'name' => 'Cardiología', 'description' => '', 'status' => true],
            ['id' => 4, 'name' => 'Pediatría', 'description' => '', 'status' => true],
            ['id' => 5, 'name' => 'Dermatología', 'description' => '', 'status' => true],
            ['id' => 6, 'name' => 'Ginecología', 'description' => '', 'status' => true],
            ['id' => 7, 'name' => 'Otorrinolaringología', 'description' => '', 'status' => true],
            ['id' => 8, 'name' => 'Oftalmología', 'description' => '', 'status' => true],
            ['id' => 9, 'name' => 'Psiquiatría', 'description' => '', 'status' => true],
            ['id' => 10, 'name' => 'Traumatología', 'description' => '', 'status' => true],
            ['id' => 11, 'name' => 'Urología', 'description' => '', 'status' => true],
            ['id' => 12, 'name' => 'Ortopedista y Traumatólogia', 'description' => '', 'status' => true],
            ['id' => 13, 'name' => 'Odontólogia', 'description' => '', 'status' => true],
            ['id' => 14, 'name' => 'Urólogia', 'description' => '', 'status' => true],
            ['id' => 15, 'name' => 'Cirujano Plástico', 'description' => '', 'status' => true],
            ['id' => 16, 'name' => 'Internista', 'description' => '', 'status' => true],
            ['id' => 17, 'name' => 'Endocrinólogia', 'description' => '', 'status' => true],
            ['id' => 18, 'name' => 'Neurólogia', 'description' => '', 'status' => true],
            ['id' => 19, 'name' => 'Gastroenterólogia', 'description' => '', 'status' => true],
            ['id' => 20, 'name' => 'Cirujano General', 'description' => '', 'status' => true],
            ['id' => 21, 'name' => 'Neurocirujano', 'description' => '', 'status' => true],
            ['id' => 22, 'name' => 'Nutricionista', 'description' => '', 'status' => true],
            ['id' => 23, 'name' => 'Fisioterapeuta', 'description' => '', 'status' => true],
            ['id' => 24, 'name' => 'Terapeuta Complementario', 'description' => '', 'status' => true],
            ['id' => 25, 'name' => 'Alergólogia', 'description' => '', 'status' => true],
            ['id' => 26, 'name' => 'Reumatólogia', 'description' => '', 'status' => true],
            ['id' => 27, 'name' => 'Neumólogia', 'description' => '', 'status' => true],
            ['id' => 28, 'name' => 'Cirujano Maxilofacial', 'description' => '', 'status' => true],
            ['id' => 29, 'name' => 'Cirujano Vascular', 'description' => '', 'status' => true],
            ['id' => 30, 'name' => 'Médico Alternativo', 'description' => '', 'status' => true],
            ['id' => 31, 'name' => 'Fonoaudiílogia', 'description' => '', 'status' => true],
            ['id' => 32, 'name' => 'Médico Fisiatra Rehabilitador', 'description' => '', 'status' => true],
            ['id' => 33, 'name' => 'Nefrólogia', 'description' => '', 'status' => true],
            ['id' => 34, 'name' => 'Médico Estetico', 'description' => '', 'status' => true],
            ['id' => 35, 'name' => 'Sexologia', 'description' => '', 'status' => true],
            ['id' => 36, 'name' => 'Hematólogia', 'description' => '', 'status' => true],
            ['id' => 37, 'name' => 'Infectólogia', 'description' => '', 'status' => true],
            ['id' => 38, 'name' => 'Neuropsicólogia', 'description' => '', 'status' => true],   
            ['id' => 39, 'name' => 'oncólogo', 'description' => '', 'status' => true], 
            ['id' => 40, 'name' => 'Endocrinólogia Pediátrica', 'description' => '', 'status' => true],
            ['id' => 41, 'name' => 'Neurólogia Pediátrica', 'description' => '', 'status' => true],
            ['id' => 42, 'name' => 'Nutriólogia', 'description' => '', 'status' => true],
            ['id' => 43, 'name' => 'Neumólogia Pediátrica', 'description' => '', 'status' => true],
            ['id' => 44, 'name' => 'Médico Laboral', 'description' => '', 'status' => true],
            ['id' => 45, 'name' => 'Radiologia', 'description' => '', 'status' => true],
            ['id' => 46, 'name' => 'Especialista en Medicina Deportiva', 'description' => '', 'status' => true],
            ['id' => 47, 'name' => 'Cirujano Pediátrico', 'description' => '', 'status' => true],
            ['id' => 48, 'name' => 'Geriatra', 'description' => '', 'status' => true],
            ['id' => 49, 'name' => 'Cirujano de Cabeza y Cuello', 'description' => '', 'status' => true],
            ['id' => 50, 'name' => 'Anestesiólogia', 'description' => '', 'status' => true],
            ['id' => 51, 'name' => 'Cirujano Cardiovascular', 'description' => '', 'status' => true],
            ['id' => 52, 'name' => 'Mastológia', 'description' => '', 'status' => true],
            ['id' => 53, 'name' => 'Especialista en Medicina Familiar', 'description' => '', 'status' => true],
            ['id' => 54, 'name' => 'Podólogo', 'description' => '', 'status' => true],
            ['id' => 55, 'name' => 'Genetista', 'description' => '', 'status' => true],
            ['id' => 56, 'name' => 'Protólogo', 'description' => '', 'status' => true],
            ['id' => 57, 'name' => 'Terapeuta Ocupacional', 'description' => '', 'status' => true],
            ['id' => 58, 'name' => 'Especialista en Tratamiento del Dolor', 'description' => '', 'status' => true],
            ['id' => 59, 'name' => 'Audiólogia', 'description' => '', 'status' => true],
            ['id' => 60, 'name' => 'Cirujano de Tórax', 'description' => '', 'status' => true],
            ['id' => 61, 'name' => 'Nefrólogia Pediátrica', 'description' => '', 'status' => true],
            ['id' => 62, 'name' => 'Coloproctólogia', 'description' => '', 'status' => true],
            ['id' => 63, 'name' => 'Tecnico en Laboratorio', 'description' => '', 'status' => true],
            ['id' => 64, 'name' => 'Hepatólogia', 'description' => '', 'status' => true],
            ['id' => 65, 'name' => 'Gastroenterólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 66, 'name' => 'Toxicólogia', 'description' => '', 'status' => true],
            ['id' => 67, 'name' => 'Terapeuta Respiratorio', 'description' => '', 'status' => true],
            ['id' => 68, 'name' => 'Especialista en Cuidados Críticos', 'description' => '', 'status' => true],
            ['id' => 69, 'name' => 'Ortopedista Infantil', 'description' => '', 'status' => true],
            ['id' => 70, 'name' => 'Cardiólogia Pediátrica', 'description' => '', 'status' => true],
            ['id' => 71, 'name' => 'Cirujano de Mama y Tejidos Blandos', 'description' => '', 'status' => true],
            ['id' => 72, 'name' => 'Oftalmólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 73, 'name' => 'Epidemiólogia', 'description' => '', 'status' => true],
            ['id' => 74, 'name' => 'Psiquiatra Infantil', 'description' => '', 'status' => true],
            ['id' => 75, 'name' => 'Neurofisiólogia', 'description' => '', 'status' => true],
            ['id' => 76, 'name' => 'Infectólogo Pediatra', 'description' => '', 'status' => true],
            ['id' => 77, 'name' => 'Oncólogo Radioterápico', 'description' => '', 'status' => true],
            ['id' => 78, 'name' => 'Alergólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 79, 'name' => 'Especialista en Medicina Nuclear', 'description' => '', 'status' => true],
            ['id' => 80, 'name' => 'Especialista en Medicina Domiciliaria', 'description' => '', 'status' => true],
            ['id' => 81, 'name' => 'Psicoanalista', 'description' => '', 'status' => true],
            ['id' => 82, 'name' => 'Médico Vascular', 'description' => '', 'status' => true],
            ['id' => 83, 'name' => 'Enfermero', 'description' => '', 'status' => true],
            ['id' => 84, 'name' => 'Especialista en Medicina de Urgencias', 'description' => '', 'status' => true],
            ['id' => 85, 'name' => 'Neuro Oftalmólogo', 'description' => '', 'status' => true],
            ['id' => 86, 'name' => 'Perinatólogo', 'description' => '', 'status' => true],
            ['id' => 87, 'name' => 'Urólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 88, 'name' => 'Auxiliar de Enfermería', 'description' => '', 'status' => true],
            ['id' => 89, 'name' => 'Ortodoncista', 'description' => '', 'status' => true],
            ['id' => 90, 'name' => 'Reumatólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 91, 'name' => 'Dermatólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 92, 'name' => 'Especialista en Salud Pública', 'description' => '', 'status' => true],
            ['id' => 93, 'name' => 'Radioterapeuta', 'description' => '', 'status' => true],
            ['id' => 94, 'name' => 'Psicopedagogo', 'description' => '', 'status' => true],
            ['id' => 95, 'name' => 'Especialista en Medicina Aeroespacial', 'description' => '', 'status' => true],
            ['id' => 96, 'name' => 'Odontopediatria', 'description' => '', 'status' => true],
            ['id' => 97, 'name' => 'Homeópata', 'description' => '', 'status' => true],
            ['id' => 98, 'name' => 'Oncólogo Pediátrico', 'description' => '', 'status' => true],
            ['id' => 99, 'name' => 'Cirujano Oncólogo', 'description' => '', 'status' => true],
            ['id' => 100, 'name' => 'Bacteriólogo', 'description' => '', 'status' => true],            
        ];

        foreach ($specialties as $specialty) {
            Specialty::firstOrCreate($specialty);
        }
    }
}
