//esta linea no va, es solo para indicar el inicio del archivo de configuración de Apache para opendoctor.online
//se crea el archivo con este comando: sudo nano /etc/httpd/conf.d/opendoctor.online.conf

<VirtualHost *:80>
    ServerName opendoctor.online
    ServerAlias ://opendoctor.online
    DocumentRoot /var/www/html/public

    <Directory /var/www/html/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php

    ErrorLog /var/log/httpd/opendoctor.online-error.log
    CustomLog /var/log/httpd/opendoctor.online-access.log combined
</VirtualHost>

