[program:laravel-queue-low]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work database-low --sleep=5 --tries=3 --timeout=300
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/laravel/queue-low.log
stopwaitsecs=3600
environment=LARAVEL_LOGLEVEL=debug
